import raw from "@/.claude/skills/187gsap/references/EFFECT-REGISTRY.json";

/**
 * Canonical source: .claude/skills/187gsap/references/EFFECT-REGISTRY.json,
 * generated by scripts/parse-motion-registry.py from
 * docs/handoffs/187-motion-gsap-skill-registry-v3.md. Read directly rather
 * than duplicated into lib/ or public/ so there is one file to regenerate,
 * not two that can drift.
 */
export type MotionSkillId = "187gsap" | "187scroll" | "187type" | "187hero" | "187model" | "187viz" | "187audio";

export interface MotionRegistryEntry {
  id: number;
  command: string;
  sourceResource: string | null;
  name: string;
  logic: string;
  triggers: string[];
  hybrid: boolean;
  owner: MotionSkillId;
}

interface RawEntry {
  id: number;
  command: string;
  source_resource: string | null;
  name: string;
  logic: string;
  triggers: string;
  hybrid: boolean;
  owner: string;
}

function parseTriggers(value: string): string[] {
  const matches = value.match(/"([^"]+)"/g) ?? [];
  return matches.map((m) => m.slice(1, -1));
}

const rawEntries = raw.entries as RawEntry[];

export const MOTION_REGISTRY: MotionRegistryEntry[] = rawEntries.map((e) => ({
  id: e.id,
  command: e.command,
  sourceResource: e.source_resource,
  name: e.name,
  logic: e.logic,
  triggers: parseTriggers(e.triggers),
  hybrid: e.hybrid,
  owner: e.owner as MotionSkillId,
}));

export const MOTION_REGISTRY_OWNERS: MotionSkillId[] = [
  "187gsap",
  "187scroll",
  "187type",
  "187hero",
  "187model",
  "187viz",
  "187audio",
];

export function motionRegistryCountByOwner(): Record<MotionSkillId, number> {
  const counts = Object.fromEntries(MOTION_REGISTRY_OWNERS.map((o) => [o, 0])) as Record<MotionSkillId, number>;
  for (const entry of MOTION_REGISTRY) counts[entry.owner] += 1;
  return counts;
}
