/**
 * Site-wide version identity (187VERSION).
 * Regenerated by `node scripts/stamp-version.mjs` before builds.
 */
import stamp from "./generated/site-build.json";

export type SiteBuildStamp = {
  name: string;
  version: string;
  packageName: string;
  builtAt: string;
  gitSha: string;
  gitShort: string;
  branch: string;
  channel: string;
  siteUrl: string;
  label: string;
};

export const siteBuild: SiteBuildStamp = stamp as SiteBuildStamp;

export function siteVersionLabel(): string {
  return siteBuild.label;
}

export function siteVersionSummary(): string {
  return `${siteBuild.name} ${siteBuild.label} · ${siteBuild.channel} · ${siteBuild.builtAt.slice(0, 10)}`;
}
